### ISSUE TITLE
Community Use/License Question

### ISSUE THREAD

**Issue by winkingcatstudio** [brett-o-d/limithron-mork-borg-character-creator#29]
Hi, was wondering if you have a license for your generator? I wanted to fork it and reuse the great work you've done so far to create a generator for other Borg-like systems like Frontier Scum and others. Happy to give you some credit like "Based off of..." if you want, just let me know what to include if you want that. Thanks for taking the time to respond, didn't see any other contact methods in your profile.

**Comment by brett-o-d** [comment]
You have permission to fork my code with attribution :) . I won't say it's the prettiest code though but it's very simple hosting. All of the game content is under the Mork Borg/Pirate Borg license. 

You can find me on the Limithron discord if you need to reach out again.

**Comment by winkingcatstudio** [comment]
Thanks! I think I'll probably build from ground up after all, but I'll hit you up on the discord in the future; cheers!
